# Generated by Django 2.0.2 on 2018-02-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('resEducation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Education')),
                ('resExperience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Experience')),
            ],
        ),
    ]
