# Generated by Django 2.0.2 on 2018-02-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resEducation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resExperience',
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
